Add nxp-wlan patch for kernel 5.15.160
Since the update to kernel 5.15.160 we get the following building error

/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_eth_ioctl.c: In function
‘woal_priv_get_ap’:
/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_eth_ioctl.c:5968:39: error:
invalid application of ‘sizeof’ to incomplete type ‘char[]’
 5968 |                                 sizeof(mwr-u.ap_addr.sa_data));

This is caused by kernel patch b5f0de6df6dc("net: dev: Convert sa_data
to flexible array in struct sockaddr"), now anything using
sizeof(sa->sa_data) must switch to sizeof(sa->sa_data_min).