Fix cyclonedx build of gcc-source
When building with
CYCLONEDX_RUNTIME_PACKAGES_ONLY = "0"`
we get the following error message.
ERROR: core-image-1.0-r0 do_rootfs: CycloneDX PN file not found:
gcc-source-13.4.0.json

This seems to be causes by the PACKAGE_ARCH ="all" of gcc-source.

We try to fix this mainline in the meta-cyclonedx layer and only build
runtime packages for now.