Fix qt6 ptest building error
There where changes specific to so fsimx93 that seem to be applied to
all boards or else the qt6 build will fail.
So we move them to the fus-common distro include.

Fixes:
Exception: FileNotFoundError: [Errno 2] No such file or directory:
'/home/developer/yocto-fus/build-wayland-fsimx8mm/tmp/work/cortexa53-mx8mm-fslc-linux/qtbase/6.10.0/build-ptest'